// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// firstzero_ac_cpp
int firstzero_ac_cpp(NumericVector y);
RcppExport SEXP _tsfeatures_firstzero_ac_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(firstzero_ac_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
// sampenc_cpp
double sampenc_cpp(NumericVector y, int M, double r);
RcppExport SEXP _tsfeatures_sampenc_cpp(SEXP ySEXP, SEXP MSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(sampenc_cpp(y, M, r));
    return rcpp_result_gen;
END_RCPP
}
// sampen_first_cpp
double sampen_first_cpp(NumericVector y);
RcppExport SEXP _tsfeatures_sampen_first_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sampen_first_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
// walker_propcross_cpp
double walker_propcross_cpp(NumericVector y, double p);
RcppExport SEXP _tsfeatures_walker_propcross_cpp(SEXP ySEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(walker_propcross_cpp(y, p));
    return rcpp_result_gen;
END_RCPP
}
// localsimple_taures_cpp
int localsimple_taures_cpp(NumericVector y, std::string forecastMeth, int trainLength);
RcppExport SEXP _tsfeatures_localsimple_taures_cpp(SEXP ySEXP, SEXP forecastMethSEXP, SEXP trainLengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type forecastMeth(forecastMethSEXP);
    Rcpp::traits::input_parameter< int >::type trainLength(trainLengthSEXP);
    rcpp_result_gen = Rcpp::wrap(localsimple_taures_cpp(y, forecastMeth, trainLength));
    return rcpp_result_gen;
END_RCPP
}
// fluctanal_prop_r1_cpp
double fluctanal_prop_r1_cpp(NumericVector x);
RcppExport SEXP _tsfeatures_fluctanal_prop_r1_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fluctanal_prop_r1_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// firstmin_ac_cpp
double firstmin_ac_cpp(NumericVector y);
RcppExport SEXP _tsfeatures_firstmin_ac_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(firstmin_ac_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
// spreadrandomlocal_meantaul_cpp
double spreadrandomlocal_meantaul_cpp(NumericVector y, int l, IntegerVector starts);
RcppExport SEXP _tsfeatures_spreadrandomlocal_meantaul_cpp(SEXP ySEXP, SEXP lSEXP, SEXP startsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    rcpp_result_gen = Rcpp::wrap(spreadrandomlocal_meantaul_cpp(y, l, starts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsfeatures_firstzero_ac_cpp", (DL_FUNC) &_tsfeatures_firstzero_ac_cpp, 1},
    {"_tsfeatures_sampenc_cpp", (DL_FUNC) &_tsfeatures_sampenc_cpp, 3},
    {"_tsfeatures_sampen_first_cpp", (DL_FUNC) &_tsfeatures_sampen_first_cpp, 1},
    {"_tsfeatures_walker_propcross_cpp", (DL_FUNC) &_tsfeatures_walker_propcross_cpp, 2},
    {"_tsfeatures_localsimple_taures_cpp", (DL_FUNC) &_tsfeatures_localsimple_taures_cpp, 3},
    {"_tsfeatures_fluctanal_prop_r1_cpp", (DL_FUNC) &_tsfeatures_fluctanal_prop_r1_cpp, 1},
    {"_tsfeatures_firstmin_ac_cpp", (DL_FUNC) &_tsfeatures_firstmin_ac_cpp, 1},
    {"_tsfeatures_spreadrandomlocal_meantaul_cpp", (DL_FUNC) &_tsfeatures_spreadrandomlocal_meantaul_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsfeatures(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
