# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' First zero crossing of the autocorrelation function
#' @param y the input time series
firstzero_ac_cpp <- function(y) {
    .Call('_tsfeatures_firstzero_ac_cpp', PACKAGE = 'tsfeatures', y)
}

#' Sample entropy counting
#' @param y the input time series
#' @param M embedding dimension
#' @param r threshold
sampenc_cpp <- function(y, M = 6L, r = 0.3) {
    .Call('_tsfeatures_sampenc_cpp', PACKAGE = 'tsfeatures', y, M, r)
}

#' C++ replacement for sampen_first
#' @param y the input time series
sampen_first_cpp <- function(y) {
    .Call('_tsfeatures_sampen_first_cpp', PACKAGE = 'tsfeatures', y)
}

#' Hypothetical walker crossing fraction
#' @param y the input time series
#' @param p the particle gap
walker_propcross_cpp <- function(y, p = 0.1) {
    .Call('_tsfeatures_walker_propcross_cpp', PACKAGE = 'tsfeatures', y, p)
}

#' Local simple forecasting residual tau
#' @param y the input time series
#' @param forecastMeth the forecasting method, defaults to \code{mean}.
#' @param trainLength the training length. Defaults to \code{-1}
localsimple_taures_cpp <- function(y, forecastMeth = "mean", trainLength = -1L) {
    .Call('_tsfeatures_localsimple_taures_cpp', PACKAGE = 'tsfeatures', y, forecastMeth, trainLength)
}

#' Fluctuation analysis
#' @param y the input time series
fluctanal_prop_r1_cpp <- function(x) {
    .Call('_tsfeatures_fluctanal_prop_r1_cpp', PACKAGE = 'tsfeatures', x)
}

#' First local minimum of the ACF
#' @param y the input time series
firstmin_ac_cpp <- function(y) {
    .Call('_tsfeatures_firstmin_ac_cpp', PACKAGE = 'tsfeatures', y)
}

#' Bootstrap stationarity measure
#' @param y the input time series
#' @param l the length of local time-series segments to analyse as a positive integer. Can also be a specified character string: "ac2": twice the first zero-crossing of the autocorrelation function
#' @param starts start indices
spreadrandomlocal_meantaul_cpp <- function(y, l, starts) {
    .Call('_tsfeatures_spreadrandomlocal_meantaul_cpp', PACKAGE = 'tsfeatures', y, l, starts)
}

