# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

firstzero_ac_cpp <- function(y) {
    .Call('_tsfeatures_firstzero_ac_cpp', PACKAGE = 'tsfeatures', y)
}

sampenc_cpp <- function(y, M = 6L, r = 0.3) {
    .Call('_tsfeatures_sampenc_cpp', PACKAGE = 'tsfeatures', y, M, r)
}

sampen_first_cpp <- function(y) {
    .Call('_tsfeatures_sampen_first_cpp', PACKAGE = 'tsfeatures', y)
}

walker_propcross_cpp <- function(y, p = 0.1) {
    .Call('_tsfeatures_walker_propcross_cpp', PACKAGE = 'tsfeatures', y, p)
}

localsimple_taures_cpp <- function(y, forecastMeth = "mean", trainLength = -1L) {
    .Call('_tsfeatures_localsimple_taures_cpp', PACKAGE = 'tsfeatures', y, forecastMeth, trainLength)
}

fluctanal_prop_r1_cpp <- function(x) {
    .Call('_tsfeatures_fluctanal_prop_r1_cpp', PACKAGE = 'tsfeatures', x)
}

firstmin_ac_cpp <- function(y) {
    .Call('_tsfeatures_firstmin_ac_cpp', PACKAGE = 'tsfeatures', y)
}

spreadrandomlocal_meantaul_cpp <- function(y, l, starts) {
    .Call('_tsfeatures_spreadrandomlocal_meantaul_cpp', PACKAGE = 'tsfeatures', y, l, starts)
}

